// sdk/react/ExoGridChart.jsx
import React, { useEffect, useState, useRef } from 'react';
import { ExoGrid } from '../../js/index.js';

export const ExoGridChart = ({ host = 'localhost', port = 9090 }) => {
    const [matrix, setMatrix] = useState(null);
    const [ticks, setTicks] = useState(0);
    const [connected, setConnected] = useState(false);
    const exoRef = useRef(null);

    useEffect(() => {
        const exo = new ExoGrid({ host, port });

        exo.on('connected', () => setConnected(true));
        exo.on('disconnected', () => setConnected(false));
        exo.on('matrix', (data) => setMatrix(data));
        exo.on('tick', () => setTicks(t => t + 1));

        exoRef.current = exo;
        exo.connect();

        return () => exo.disconnect();
    }, [host, port]);

    return (
        <div className="exogrid-chart">
            <div className="status">
                <span className={`indicator ${connected ? 'connected' : 'disconnected'}`} />
                {connected ? 'Connected' : 'Disconnected'}
            </div>
            <div className="stats">
                <div>Ticks: {ticks}</div>
                {matrix && (
                    <>
                        <div>POC: ${matrix.poc_price?.toFixed(2)}</div>
                        <div>Volume: {matrix.total_volume}</div>
                    </>
                )}
            </div>
            <canvas id="chart" width={800} height={600} />
        </div>
    );
};

export default ExoGridChart;

// sdk/svelte/ExoGridChart.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import { ExoGrid } from '../../js/index.js';

  export let host = 'localhost';
  export let port = 9090;

  let exo;
  let connected = false;
  let tickCount = 0;
  let matrix = null;

  onMount(() => {
    exo = new ExoGrid({ host, port });

    exo.on('connected', () => {
      connected = true;
    });

    exo.on('disconnected', () => {
      connected = false;
    });

    exo.on('tick', () => {
      tickCount++;
    });

    exo.on('matrix', (data) => {
      matrix = data;
    });

    exo.connect();
  });

  onDestroy(() => {
    if (exo) exo.disconnect();
  });
</script>

<div class="exogrid-chart">
  <div class="status" class:connected class:disconnected={!connected}>
    {connected ? '✓ Connected' : '✗ Disconnected'}
  </div>

  <div class="stats">
    <div>Ticks: {tickCount}</div>
    {#if matrix}
      <div>POC: ${matrix.poc_price?.toFixed(2)}</div>
      <div>Volume: {matrix.total_volume}</div>
    {/if}
  </div>

  <canvas id="chart" width="800" height="600" />
</div>

<style>
  .exogrid-chart {
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 8px;
  }

  .status {
    font-weight: bold;
    margin-bottom: 10px;
  }

  .connected {
    color: #4caf50;
  }

  .disconnected {
    color: #f44336;
  }

  .stats {
    display: flex;
    gap: 20px;
    margin-bottom: 20px;
  }

  canvas {
    border: 1px solid #ddd;
  }
</style>
